package codegen

import (
	"fmt"
	"strings"

	"github.com/opd-ai/go2c/internal/llvm"
)

// Emitter generates C code from LLVM IR
type Emitter struct {
	typeMapper *TypeMapper
	includes   []string
	defines    []string
}

// NewEmitter creates a new C code emitter
func NewEmitter() *Emitter {
	return &Emitter{
		typeMapper: NewTypeMapper(),
		includes: []string{
			"stdio.h",
			"stdlib.h",
			"string.h",
			"stdint.h",
			"stdbool.h",
		},
		defines: []string{},
	}
}

// Emit generates C code from an LLVM module
func (e *Emitter) Emit(module *llvm.Module) (string, error) {
	var sb strings.Builder

	// Write file header comment
	sb.WriteString("// Generated by go2c - Go to C transpiler\n")
	sb.WriteString("// DO NOT EDIT - Generated code\n\n")

	// Write includes
	for _, include := range e.includes {
		sb.WriteString(fmt.Sprintf("#include <%s>\n", include))
	}
	sb.WriteString("\n")

	// Write defines
	for _, define := range e.defines {
		sb.WriteString(fmt.Sprintf("#define %s\n", define))
	}
	if len(e.defines) > 0 {
		sb.WriteString("\n")
	}

	// Write forward declarations for user functions
	analyzer := llvm.NewAnalyzer(module)
	userFunctions := analyzer.GetUserFunctions()
	
	if len(userFunctions) > 0 {
		sb.WriteString("// Forward declarations\n")
		for _, fn := range userFunctions {
			decl := e.generateFunctionDeclaration(fn)
			sb.WriteString(decl + ";\n")
		}
		sb.WriteString("\n")
	}

	// Write global variables
	if len(module.Globals) > 0 {
		sb.WriteString("// Global variables\n")
		for _, global := range module.Globals {
			globalDecl := e.generateGlobalVariable(global)
			if globalDecl != "" {
				sb.WriteString(globalDecl + "\n")
			}
		}
		sb.WriteString("\n")
	}

	// Write function definitions
	sb.WriteString("// Function implementations\n")
	for _, fn := range userFunctions {
		fnCode := e.generateFunction(fn)
		sb.WriteString(fnCode)
		sb.WriteString("\n")
	}

	return sb.String(), nil
}

// generateFunctionDeclaration generates a C function declaration
func (e *Emitter) generateFunctionDeclaration(fn *llvm.Function) string {
	returnType := e.typeMapper.LLVMTypeToC(fn.ReturnType)
	funcName := e.typeMapper.SanitizeName(fn.Name)

	// Build parameter list
	params := []string{}
	if len(fn.Parameters) == 0 {
		params = append(params, "void")
	} else {
		for i, param := range fn.Parameters {
			paramType := e.typeMapper.LLVMTypeToC(param.Type)
			paramName := e.typeMapper.SanitizeName(param.Name)
			if paramName == "" {
				paramName = fmt.Sprintf("param%d", i)
			}
			params = append(params, fmt.Sprintf("%s %s", paramType, paramName))
		}
	}

	return fmt.Sprintf("%s %s(%s)", returnType, funcName, strings.Join(params, ", "))
}

// generateFunction generates a complete C function
func (e *Emitter) generateFunction(fn *llvm.Function) string {
	var sb strings.Builder

	// Function declaration
	sb.WriteString(e.generateFunctionDeclaration(fn))
	sb.WriteString(" {\n")

	// Function body
	if len(fn.Body) == 0 {
		sb.WriteString("    // Empty function body\n")
	} else {
		// Basic instruction conversion
		for _, line := range fn.Body {
			cLine := e.convertInstructionToC(line)
			if cLine != "" {
				sb.WriteString("    " + cLine + "\n")
			}
		}
	}

	sb.WriteString("}\n")
	return sb.String()
}

// convertInstructionToC converts an LLVM instruction to C code
func (e *Emitter) convertInstructionToC(instruction string) string {
	instruction = strings.TrimSpace(instruction)

	// Skip empty lines
	if instruction == "" {
		return ""
	}

	// Handle return instructions
	if strings.HasPrefix(instruction, "ret") {
		parts := strings.Fields(instruction)
		if len(parts) == 1 || parts[1] == "void" {
			return "return;"
		}
		// ret i32 0
		if len(parts) >= 3 {
			return fmt.Sprintf("return %s;", parts[2])
		}
		return "return;"
	}

	// Handle call instructions
	if strings.Contains(instruction, "call") {
		return e.convertCallInstruction(instruction)
	}

	// Handle alloca (stack allocation)
	if strings.Contains(instruction, "alloca") {
		return "/* alloca - stack allocation */"
	}

	// Handle store instructions
	if strings.HasPrefix(instruction, "store") {
		return "/* store instruction */"
	}

	// Handle load instructions
	if strings.Contains(instruction, "load") {
		return "/* load instruction */"
	}

	// Handle branch instructions
	if strings.HasPrefix(instruction, "br") {
		return e.convertBranchInstruction(instruction)
	}

	// Handle label declarations
	if strings.HasSuffix(instruction, ":") {
		labelName := strings.TrimSuffix(instruction, ":")
		labelName = e.typeMapper.SanitizeName(labelName)
		return fmt.Sprintf("%s:", labelName)
	}

	// Default: comment out unknown instructions
	return fmt.Sprintf("/* %s */", instruction)
}

// convertCallInstruction converts a call instruction to C
func (e *Emitter) convertCallInstruction(instruction string) string {
	// Simple call conversion - extract function name and basic parameters
	// Example: call void @puts(i8* %1)
	if strings.Contains(instruction, "@") {
		parts := strings.Split(instruction, "@")
		if len(parts) > 1 {
			funcPart := parts[1]
			funcName := strings.Split(funcPart, "(")[0]
			funcName = e.typeMapper.SanitizeName(funcName)
			
			// Check if this is a known function
			if funcName == "puts" {
				return fmt.Sprintf("%s(/* args */);", funcName)
			}
			
			return fmt.Sprintf("%s(/* args */);", funcName)
		}
	}
	return "/* call instruction */"
}

// convertBranchInstruction converts a branch instruction to C
func (e *Emitter) convertBranchInstruction(instruction string) string {
	// br label %label1 -> goto label1;
	if strings.Contains(instruction, "label") {
		parts := strings.Fields(instruction)
		for i, part := range parts {
			if part == "label" && i+1 < len(parts) {
				label := e.typeMapper.SanitizeName(parts[i+1])
				return fmt.Sprintf("goto %s;", label)
			}
		}
	}
	// Conditional branch: br i1 %cond, label %true, label %false
	if strings.Contains(instruction, ",") {
		return "/* conditional branch - if/goto */"
	}
	return "/* branch instruction */"
}

// generateGlobalVariable generates a C global variable declaration
func (e *Emitter) generateGlobalVariable(global *llvm.Global) string {
	name := e.typeMapper.SanitizeName(global.Name)
	
	// Handle string constants
	if strings.Contains(global.Value, "constant") && strings.Contains(global.Value, "c\"") {
		// Extract string value
		if idx := strings.Index(global.Value, "c\""); idx != -1 {
			strPart := global.Value[idx+2:]
			if endIdx := strings.Index(strPart, "\""); endIdx != -1 {
				strValue := strPart[:endIdx]
				// Unescape common escapes
				strValue = strings.ReplaceAll(strValue, "\\00", "\\0")
				strValue = strings.ReplaceAll(strValue, "\\0A", "\\n")
				return fmt.Sprintf("static const char %s[] = \"%s\";", name, strValue)
			}
		}
	}
	
	// Default handling for other globals
	return fmt.Sprintf("/* Global: %s */", name)
}

// AddInclude adds a custom include file
func (e *Emitter) AddInclude(include string) {
	e.includes = append(e.includes, include)
}

// AddDefine adds a preprocessor define
func (e *Emitter) AddDefine(define string) {
	e.defines = append(e.defines, define)
}
