package codegen

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/opd-ai/go2c/internal/llvm"
)

// Emitter generates C code from LLVM IR
type Emitter struct {
	typeMapper *TypeMapper
	includes   []string
	defines    []string
}

// NewEmitter creates a new C code emitter
func NewEmitter() *Emitter {
	return &Emitter{
		typeMapper: NewTypeMapper(),
		includes: []string{
			"stdio.h",
			"stdlib.h",
			"string.h",
			"stdint.h",
			"stdbool.h",
		},
		defines: []string{},
	}
}

// Emit generates C code from an LLVM module
func (e *Emitter) Emit(module *llvm.Module) (string, error) {
	var sb strings.Builder

	// Write file header comment
	sb.WriteString("// Generated by go2c - Go to C transpiler\n")
	sb.WriteString("// DO NOT EDIT - Generated code\n\n")

	// Write includes
	for _, include := range e.includes {
		sb.WriteString(fmt.Sprintf("#include <%s>\n", include))
	}
	sb.WriteString("\n")

	// Write defines
	for _, define := range e.defines {
		sb.WriteString(fmt.Sprintf("#define %s\n", define))
	}
	if len(e.defines) > 0 {
		sb.WriteString("\n")
	}

	// First pass: process all functions to discover aggregate types
	analyzer := llvm.NewAnalyzer(module)
	userFunctions := analyzer.GetUserFunctions()
	
	for _, fn := range userFunctions {
		// Register aggregate return types
		if e.typeMapper.IsAggregateType(fn.ReturnType) {
			e.typeMapper.LLVMTypeToC(fn.ReturnType)
		}
		// Register aggregate parameter types
		for _, param := range fn.Parameters {
			if e.typeMapper.IsAggregateType(param.Type) {
				e.typeMapper.LLVMTypeToC(param.Type)
			}
		}
	}

	// Write aggregate type definitions (structs for multiple return values)
	aggregateTypes := e.typeMapper.GetAggregateTypes()
	if len(aggregateTypes) > 0 {
		sb.WriteString("// Aggregate type definitions (for multiple return values)\n")
		for _, aggType := range aggregateTypes {
			structDef := e.generateAggregateTypeDefinition(aggType)
			sb.WriteString(structDef + "\n")
		}
		sb.WriteString("\n")
	}

	// Write forward declarations for user functions
	if len(userFunctions) > 0 {
		sb.WriteString("// Forward declarations\n")
		for _, fn := range userFunctions {
			decl := e.generateFunctionDeclaration(fn)
			sb.WriteString(decl + ";\n")
		}
		sb.WriteString("\n")
	}

	// Write global variables
	if len(module.Globals) > 0 {
		sb.WriteString("// Global variables\n")
		for _, global := range module.Globals {
			globalDecl := e.generateGlobalVariable(global)
			if globalDecl != "" {
				sb.WriteString(globalDecl + "\n")
			}
		}
		sb.WriteString("\n")
	}

	// Write function definitions
	sb.WriteString("// Function implementations\n")
	for _, fn := range userFunctions {
		fnCode := e.generateFunction(fn)
		sb.WriteString(fnCode)
		sb.WriteString("\n")
	}

	return sb.String(), nil
}

// generateFunctionDeclaration generates a C function declaration
func (e *Emitter) generateFunctionDeclaration(fn *llvm.Function) string {
	returnType := e.typeMapper.LLVMTypeToC(fn.ReturnType)
	funcName := e.typeMapper.SanitizeName(fn.Name)

	// Build parameter list
	params := []string{}
	if len(fn.Parameters) == 0 {
		params = append(params, "void")
	} else {
		for i, param := range fn.Parameters {
			paramType := e.typeMapper.LLVMTypeToC(param.Type)
			paramName := e.typeMapper.SanitizeName(param.Name)
			if paramName == "" {
				paramName = fmt.Sprintf("param%d", i)
			}
			params = append(params, fmt.Sprintf("%s %s", paramType, paramName))
		}
	}

	return fmt.Sprintf("%s %s(%s)", returnType, funcName, strings.Join(params, ", "))
}

// generateFunction generates a complete C function
func (e *Emitter) generateFunction(fn *llvm.Function) string {
	var sb strings.Builder

	// Function declaration
	sb.WriteString(e.generateFunctionDeclaration(fn))
	sb.WriteString(" {\n")

	// Function body
	if len(fn.Body) == 0 {
		sb.WriteString("    // Empty function body\n")
	} else {
		// Try to use enhanced control flow generation
		enhanced := e.generateFunctionWithControlFlow(fn)
		if enhanced != "" {
			sb.WriteString(enhanced)
		} else {
			// Fallback to basic instruction conversion
			for _, line := range fn.Body {
				cLine := e.convertInstructionToC(line)
				if cLine != "" {
					sb.WriteString("    " + cLine + "\n")
				}
			}
		}
	}

	sb.WriteString("}\n")
	return sb.String()
}

// convertInstructionToC converts an LLVM instruction to C code
func (e *Emitter) convertInstructionToC(instruction string) string {
	instruction = strings.TrimSpace(instruction)

	// Skip empty lines
	if instruction == "" {
		return ""
	}

	// Handle return instructions
	if strings.HasPrefix(instruction, "ret") {
		return e.convertReturnInstruction(instruction)
	}

	// Handle insertvalue instructions (for aggregate types)
	if strings.Contains(instruction, "insertvalue") {
		return e.convertInsertValueInstruction(instruction)
	}

	// Handle extractvalue instructions (for aggregate types)
	if strings.Contains(instruction, "extractvalue") {
		return e.convertExtractValueInstruction(instruction)
	}

	// Handle assignment with arithmetic operations
	// Example: %result = add i32 %a, %b
	if strings.Contains(instruction, "=") && !strings.Contains(instruction, "call") {
		return e.convertAssignmentInstruction(instruction)
	}

	// Handle call instructions
	if strings.Contains(instruction, "call") {
		return e.convertCallInstruction(instruction)
	}

	// Handle alloca (stack allocation)
	if strings.Contains(instruction, "alloca") {
		return e.convertAllocaInstruction(instruction)
	}

	// Handle store instructions
	if strings.HasPrefix(instruction, "store") {
		return e.convertStoreInstruction(instruction)
	}

	// Handle load instructions
	if strings.Contains(instruction, "load") {
		return e.convertLoadInstruction(instruction)
	}

	// Handle branch instructions
	if strings.HasPrefix(instruction, "br") {
		return e.convertBranchInstruction(instruction)
	}

	// Handle label declarations
	if strings.HasSuffix(instruction, ":") {
		labelName := strings.TrimSuffix(instruction, ":")
		labelName = e.typeMapper.SanitizeName(labelName)
		return fmt.Sprintf("%s:", labelName)
	}

	// Default: comment out unknown instructions
	return fmt.Sprintf("/* %s */", instruction)
}

// convertReturnInstruction converts a return instruction to C
func (e *Emitter) convertReturnInstruction(instruction string) string {
	instruction = strings.TrimSpace(instruction)
	
	// Handle simple "ret" or "ret void"
	if instruction == "ret" || instruction == "ret void" {
		return "return;"
	}
	
	// Parse the return instruction
	// Format: ret <type> <value>
	// Example: ret i32 0
	// Example: ret i32 %result
	// Example: ret {i32, i32} %result2
	
	parts := strings.SplitN(instruction, " ", 2)
	if len(parts) < 2 {
		return "return;"
	}
	
	rest := strings.TrimSpace(parts[1])
	
	// Find the value part - it's after the type
	// For aggregate types: {i32, i32} %result2
	// For simple types: i32 %result or i32 0
	
	var value string
	
	// Check if it starts with an aggregate type
	if strings.HasPrefix(rest, "{") {
		// Find the closing brace
		closeBrace := strings.Index(rest, "}")
		if closeBrace != -1 && closeBrace+1 < len(rest) {
			value = strings.TrimSpace(rest[closeBrace+1:])
		}
	} else {
		// Simple type - split by space
		typeParts := strings.Fields(rest)
		if len(typeParts) >= 2 {
			value = typeParts[len(typeParts)-1]
		}
	}
	
	if value == "" {
		return "return;"
	}
	
	// Check if value is a literal number
	if _, err := strconv.Atoi(value); err != nil {
		// It's a variable, sanitize it
		value = e.typeMapper.SanitizeName(value)
	}
	
	return fmt.Sprintf("return %s;", value)
}

// convertAssignmentInstruction converts an assignment instruction to C
func (e *Emitter) convertAssignmentInstruction(instruction string) string {
	// Example: %result = add i32 %a, %b
	parts := strings.SplitN(instruction, "=", 2)
	if len(parts) != 2 {
		return fmt.Sprintf("/* %s */", instruction)
	}

	lhs := strings.TrimSpace(parts[0])
	rhs := strings.TrimSpace(parts[1])
	lhs = e.typeMapper.SanitizeName(lhs)

	// Parse the operation
	rhsParts := strings.Fields(rhs)
	if len(rhsParts) == 0 {
		return fmt.Sprintf("/* %s */", instruction)
	}

	op := rhsParts[0]

	switch op {
	case "add", "sub", "mul", "sdiv", "udiv", "srem", "urem":
		if len(rhsParts) >= 4 {
			// add i32 %a, %b
			cType := e.typeMapper.LLVMTypeToC(rhsParts[1])
			operand1 := strings.TrimSuffix(e.typeMapper.SanitizeName(rhsParts[2]), ",")
			operand2 := e.typeMapper.SanitizeName(rhsParts[3])
			
			var operator string
			switch op {
			case "add":
				operator = "+"
			case "sub":
				operator = "-"
			case "mul":
				operator = "*"
			case "sdiv", "udiv":
				operator = "/"
			case "srem", "urem":
				operator = "%"
			}
			
			return fmt.Sprintf("%s %s = %s %s %s;", cType, lhs, operand1, operator, operand2)
		}
	case "icmp":
		// icmp sgt i32 %a, %b -> comparison
		if len(rhsParts) >= 5 {
			// icmp sgt i32 %a, %b
			condition := rhsParts[1]  // sgt, slt, eq, ne, etc.
			operand1 := strings.TrimSuffix(e.typeMapper.SanitizeName(rhsParts[3]), ",")
			operand2 := e.typeMapper.SanitizeName(rhsParts[4])
			
			var operator string
			switch condition {
			case "eq":
				operator = "=="
			case "ne":
				operator = "!="
			case "sgt", "ugt":
				operator = ">"
			case "sge", "uge":
				operator = ">="
			case "slt", "ult":
				operator = "<"
			case "sle", "ule":
				operator = "<="
			default:
				operator = "?" + condition + "?"
			}
			
			return fmt.Sprintf("bool %s = %s %s %s;", lhs, operand1, operator, operand2)
		}
	}

	return fmt.Sprintf("/* %s */", instruction)
}

// convertAllocaInstruction converts an alloca instruction to C
func (e *Emitter) convertAllocaInstruction(instruction string) string {
	// Example: %ptr = alloca i32
	parts := strings.SplitN(instruction, "=", 2)
	if len(parts) != 2 {
		return fmt.Sprintf("/* %s */", instruction)
	}

	lhs := strings.TrimSpace(parts[0])
	rhs := strings.TrimSpace(parts[1])
	lhs = e.typeMapper.SanitizeName(lhs)

	rhsParts := strings.Fields(rhs)
	if len(rhsParts) >= 2 && rhsParts[0] == "alloca" {
		allocType := e.typeMapper.LLVMTypeToC(rhsParts[1])
		return fmt.Sprintf("%s %s;", allocType, lhs)
	}

	return fmt.Sprintf("/* %s */", instruction)
}

// convertStoreInstruction converts a store instruction to C
func (e *Emitter) convertStoreInstruction(instruction string) string {
	// Example: store i32 %value, i32* %ptr
	parts := strings.Fields(instruction)
	if len(parts) >= 5 {
		value := e.typeMapper.SanitizeName(parts[2])
		value = strings.TrimSuffix(value, ",")
		dest := e.typeMapper.SanitizeName(parts[4])
		return fmt.Sprintf("*%s = %s;", dest, value)
	}
	return fmt.Sprintf("/* %s */", instruction)
}

// convertLoadInstruction converts a load instruction to C
func (e *Emitter) convertLoadInstruction(instruction string) string {
	// Example: %value = load i32, i32* %ptr
	parts := strings.SplitN(instruction, "=", 2)
	if len(parts) != 2 {
		return fmt.Sprintf("/* %s */", instruction)
	}

	lhs := strings.TrimSpace(parts[0])
	rhs := strings.TrimSpace(parts[1])
	lhs = e.typeMapper.SanitizeName(lhs)

	rhsParts := strings.Fields(rhs)
	if len(rhsParts) >= 3 && rhsParts[0] == "load" {
		loadType := e.typeMapper.LLVMTypeToC(rhsParts[1])
		loadType = strings.TrimSuffix(loadType, ",")
		src := e.typeMapper.SanitizeName(rhsParts[len(rhsParts)-1])
		return fmt.Sprintf("%s %s = *%s;", loadType, lhs, src)
	}

	return fmt.Sprintf("/* %s */", instruction)
}

// convertCallInstruction converts a call instruction to C
func (e *Emitter) convertCallInstruction(instruction string) string {
	// Parse call instruction
	// Example: call void @puts(i8* %1)
	// Example: %0 = call i32 @add(i32 5, i32 3)
	
	hasAssignment := strings.Contains(instruction, "=")
	var lhs string
	var callPart string
	
	if hasAssignment {
		parts := strings.SplitN(instruction, "=", 2)
		lhs = e.typeMapper.SanitizeName(strings.TrimSpace(parts[0]))
		callPart = strings.TrimSpace(parts[1])
	} else {
		callPart = instruction
	}
	
	// Extract function name
	if !strings.Contains(callPart, "@") {
		return fmt.Sprintf("/* %s */", instruction)
	}
	
	atIndex := strings.Index(callPart, "@")
	afterAt := callPart[atIndex+1:]
	parenIndex := strings.Index(afterAt, "(")
	
	if parenIndex == -1 {
		return fmt.Sprintf("/* %s */", instruction)
	}
	
	funcName := e.typeMapper.SanitizeName(afterAt[:parenIndex])
	
	// Extract arguments
	argsStart := atIndex + 1 + parenIndex + 1
	argsEnd := strings.LastIndex(callPart, ")")
	
	if argsEnd == -1 {
		argsEnd = len(callPart)
	}
	
	argsStr := ""
	if argsStart < argsEnd {
		argsPart := callPart[argsStart:argsEnd]
		args := e.parseCallArguments(argsPart)
		argsStr = strings.Join(args, ", ")
	}
	
	// Generate C code
	if hasAssignment {
		// Extract return type
		// Handle aggregate types like {i32, i32}
		callFields := strings.Fields(callPart)
		var returnType string
		
		if len(callFields) >= 2 {
			// Check if it's an aggregate type
			if strings.HasPrefix(callPart, "call") {
				// Find the type after "call"
				afterCall := strings.TrimPrefix(callPart, "call")
				afterCall = strings.TrimSpace(afterCall)
				
				// Extract type before @function_name
				atIndex := strings.Index(afterCall, "@")
				if atIndex > 0 {
					typeStr := strings.TrimSpace(afterCall[:atIndex])
					returnType = e.typeMapper.LLVMTypeToC(typeStr)
				} else {
					returnType = e.typeMapper.LLVMTypeToC(callFields[1])
				}
			} else {
				returnType = e.typeMapper.LLVMTypeToC(callFields[1])
			}
		} else {
			returnType = "int"
		}
		return fmt.Sprintf("%s %s = %s(%s);", returnType, lhs, funcName, argsStr)
	}
	
	return fmt.Sprintf("%s(%s);", funcName, argsStr)
}

// parseCallArguments parses function call arguments
func (e *Emitter) parseCallArguments(argsStr string) []string {
	if strings.TrimSpace(argsStr) == "" {
		return []string{}
	}
	
	args := []string{}
	parts := strings.Split(argsStr, ",")
	
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		
		// Parse "type value" format
		tokens := strings.Fields(part)
		if len(tokens) >= 2 {
			value := tokens[len(tokens)-1]
			// Check if value is a literal number
			if _, err := strconv.Atoi(value); err == nil {
				args = append(args, value)
			} else {
				value = e.typeMapper.SanitizeName(value)
				args = append(args, value)
			}
		} else if len(tokens) == 1 {
			value := tokens[0]
			if _, err := strconv.Atoi(value); err == nil {
				args = append(args, value)
			} else {
				value = e.typeMapper.SanitizeName(value)
				args = append(args, value)
			}
		}
	}
	
	return args
}

// convertBranchInstruction converts a branch instruction to C
func (e *Emitter) convertBranchInstruction(instruction string) string {
	// br label %label1 -> goto label1;
	if strings.Contains(instruction, "label") {
		parts := strings.Fields(instruction)
		for i, part := range parts {
			if part == "label" && i+1 < len(parts) {
				label := e.typeMapper.SanitizeName(parts[i+1])
				return fmt.Sprintf("goto %s;", label)
			}
		}
	}
	// Conditional branch: br i1 %cond, label %true, label %false
	if strings.Contains(instruction, ",") {
		return "/* conditional branch - if/goto */"
	}
	return "/* branch instruction */"
}

// generateGlobalVariable generates a C global variable declaration
func (e *Emitter) generateGlobalVariable(global *llvm.Global) string {
	name := e.typeMapper.SanitizeName(global.Name)
	
	// Handle string constants
	if strings.Contains(global.Value, "constant") && strings.Contains(global.Value, "c\"") {
		// Extract string value
		if idx := strings.Index(global.Value, "c\""); idx != -1 {
			strPart := global.Value[idx+2:]
			if endIdx := strings.Index(strPart, "\""); endIdx != -1 {
				strValue := strPart[:endIdx]
				// Unescape common escapes
				strValue = strings.ReplaceAll(strValue, "\\00", "\\0")
				strValue = strings.ReplaceAll(strValue, "\\0A", "\\n")
				return fmt.Sprintf("static const char %s[] = \"%s\";", name, strValue)
			}
		}
	}
	
	// Default handling for other globals
	return fmt.Sprintf("/* Global: %s */", name)
}

// AddInclude adds a custom include file
func (e *Emitter) AddInclude(include string) {
	e.includes = append(e.includes, include)
}

// AddDefine adds a preprocessor define
func (e *Emitter) AddDefine(define string) {
	e.defines = append(e.defines, define)
}

// generateFunctionWithControlFlow generates a function using detected control flow patterns
func (e *Emitter) generateFunctionWithControlFlow(fn *llvm.Function) string {
	// Analyze control flow
	cfa := llvm.NewControlFlowAnalyzer(fn)
	patterns, err := cfa.AnalyzeControlFlow()
	if err != nil || len(patterns) == 0 {
		return "" // Fallback to basic generation
	}
	
	// Get basic blocks
	blocks := cfa.GetBasicBlocks()
	
	// Track which blocks are part of structured control flow
	structuredBlocks := make(map[string]bool)
	for _, pattern := range patterns {
		for _, blockLabel := range pattern.Blocks {
			structuredBlocks[blockLabel] = true
		}
	}
	
	var sb strings.Builder
	
	// Generate code with structured control flow
	processedBlocks := make(map[string]bool)
	
	// Start with entry block
	e.generateBlockWithPatterns("entry", blocks, patterns, &sb, processedBlocks, 1)
	
	// Generate any remaining blocks that weren't covered
	for label, block := range blocks {
		if !processedBlocks[label] && label != "entry" {
			e.generateBasicBlock(label, block, &sb, 1)
			processedBlocks[label] = true
		}
	}
	
	return sb.String()
}

// generateBlockWithPatterns generates code for a block, checking for control flow patterns
func (e *Emitter) generateBlockWithPatterns(
	label string,
	blocks map[string]*llvm.BasicBlock,
	patterns []*llvm.ControlFlowPattern,
	sb *strings.Builder,
	processed map[string]bool,
	indent int,
) {
	if processed[label] {
		return
	}
	
	block, exists := blocks[label]
	if !exists {
		return
	}
	
	processed[label] = true
	
	// Check if this block starts a pattern
	pattern := e.findPatternStartingAt(label, patterns)
	
	if pattern != nil {
		switch pattern.Type {
		case "if-else":
			e.generateIfElse(pattern, blocks, patterns, sb, processed, indent)
		case "if-then":
			e.generateIfThen(pattern, blocks, patterns, sb, processed, indent)
		case "while":
			e.generateWhile(pattern, blocks, patterns, sb, processed, indent)
		case "for":
			e.generateFor(pattern, blocks, patterns, sb, processed, indent)
		case "switch":
			e.generateSwitch(pattern, blocks, patterns, sb, processed, indent)
		default:
			// Unknown pattern, generate as basic block
			e.generateBasicBlock(label, block, sb, indent)
		}
	} else {
		// No pattern, generate as basic block but check for continuation
		e.generateBasicBlockAndContinue(label, block, blocks, patterns, sb, processed, indent)
	}
}

// generateBasicBlockAndContinue generates a basic block and follows control flow
func (e *Emitter) generateBasicBlockAndContinue(
	label string,
	block *llvm.BasicBlock,
	blocks map[string]*llvm.BasicBlock,
	patterns []*llvm.ControlFlowPattern,
	sb *strings.Builder,
	processed map[string]bool,
	indent int,
) {
	indentStr := strings.Repeat("    ", indent)
	
	// Generate instructions before the terminator
	for i, inst := range block.Instructions {
		// Skip the last instruction if it's the terminator
		if i == len(block.Instructions)-1 && e.isTerminator(inst) {
			// Check if this is an unconditional branch to next block
			if block.Terminator != nil && block.Terminator.Type == "br_uncon" {
				nextLabel := block.Terminator.UnconLabel
				// Continue with the next block instead of generating goto
				e.generateBlockWithPatterns(nextLabel, blocks, patterns, sb, processed, indent)
				return
			}
			// Otherwise convert the terminator
			cLine := e.convertInstructionToC(inst)
			if cLine != "" {
				sb.WriteString(indentStr + cLine + "\n")
			}
			break
		}
		cLine := e.convertInstructionToC(inst)
		if cLine != "" {
			sb.WriteString(indentStr + cLine + "\n")
		}
	}
}

// isTerminator checks if an instruction is a terminator
func (e *Emitter) isTerminator(instruction string) bool {
	instruction = strings.TrimSpace(instruction)
	return strings.HasPrefix(instruction, "ret") ||
		strings.HasPrefix(instruction, "br") ||
		strings.HasPrefix(instruction, "switch") ||
		strings.HasPrefix(instruction, "unreachable")
}

// findPatternStartingAt finds a pattern that starts at the given label
func (e *Emitter) findPatternStartingAt(label string, patterns []*llvm.ControlFlowPattern) *llvm.ControlFlowPattern {
	for _, pattern := range patterns {
		if pattern.StartLabel == label {
			return pattern
		}
	}
	return nil
}

// generateIfElse generates an if-else statement
func (e *Emitter) generateIfElse(
	pattern *llvm.ControlFlowPattern,
	blocks map[string]*llvm.BasicBlock,
	patterns []*llvm.ControlFlowPattern,
	sb *strings.Builder,
	processed map[string]bool,
	indent int,
) {
	condBlock := blocks[pattern.CondBlock]
	thenBlock := blocks[pattern.ThenBlock]
	elseBlock := blocks[pattern.ElseBlock]
	
	if condBlock == nil || thenBlock == nil || elseBlock == nil {
		return
	}
	
	indentStr := strings.Repeat("    ", indent)
	
	// Generate instructions before the branch (excluding terminator)
	for i, inst := range condBlock.Instructions {
		// Skip the last instruction if it's the branch terminator
		if i == len(condBlock.Instructions)-1 && strings.HasPrefix(inst, "br") {
			break
		}
		cLine := e.convertInstructionToC(inst)
		if cLine != "" {
			sb.WriteString(indentStr + cLine + "\n")
		}
	}
	
	// Generate if statement
	if condBlock.Terminator != nil && condBlock.Terminator.Condition != "" {
		condition := e.typeMapper.SanitizeName(condBlock.Terminator.Condition)
		sb.WriteString(fmt.Sprintf("%sif (%s) {\n", indentStr, condition))
		
		// Generate then block (all instructions including terminator)
		for _, inst := range thenBlock.Instructions {
			cLine := e.convertInstructionToC(inst)
			if cLine != "" {
				sb.WriteString(strings.Repeat("    ", indent+1) + cLine + "\n")
			}
		}
		
		sb.WriteString(fmt.Sprintf("%s} else {\n", indentStr))
		
		// Generate else block (all instructions including terminator)
		for _, inst := range elseBlock.Instructions {
			cLine := e.convertInstructionToC(inst)
			if cLine != "" {
				sb.WriteString(strings.Repeat("    ", indent+1) + cLine + "\n")
			}
		}
		
		sb.WriteString(fmt.Sprintf("%s}\n", indentStr))
		
		// Mark blocks as processed
		processed[pattern.ThenBlock] = true
		processed[pattern.ElseBlock] = true
		
		// Continue with merge block if it exists
		if pattern.EndLabel != "" && !processed[pattern.EndLabel] {
			e.generateBlockWithPatterns(pattern.EndLabel, blocks, patterns, sb, processed, indent)
		}
	}
}

// buildReturnFromBlock is no longer needed - removed

// generateIfThen generates an if-then statement (no else)
func (e *Emitter) generateIfThen(
	pattern *llvm.ControlFlowPattern,
	blocks map[string]*llvm.BasicBlock,
	patterns []*llvm.ControlFlowPattern,
	sb *strings.Builder,
	processed map[string]bool,
	indent int,
) {
	condBlock := blocks[pattern.CondBlock]
	thenBlock := blocks[pattern.ThenBlock]
	
	if condBlock == nil || thenBlock == nil {
		return
	}
	
	indentStr := strings.Repeat("    ", indent)
	
	// Generate instructions before the branch (excluding terminator)
	for i, inst := range condBlock.Instructions {
		// Skip the last instruction if it's the branch terminator
		if i == len(condBlock.Instructions)-1 && strings.HasPrefix(inst, "br") {
			break
		}
		cLine := e.convertInstructionToC(inst)
		if cLine != "" {
			sb.WriteString(indentStr + cLine + "\n")
		}
	}
	
	// Generate if statement
	if condBlock.Terminator != nil && condBlock.Terminator.Condition != "" {
		condition := e.typeMapper.SanitizeName(condBlock.Terminator.Condition)
		sb.WriteString(fmt.Sprintf("%sif (%s) {\n", indentStr, condition))
		
		// Generate then block (all instructions except final unconditional branch to merge)
		for i, inst := range thenBlock.Instructions {
			// Skip unconditional branch to merge point
			if i == len(thenBlock.Instructions)-1 && strings.HasPrefix(inst, "br label") {
				break
			}
			cLine := e.convertInstructionToC(inst)
			if cLine != "" {
				sb.WriteString(strings.Repeat("    ", indent+1) + cLine + "\n")
			}
		}
		
		sb.WriteString(fmt.Sprintf("%s}\n", indentStr))
		
		// Mark blocks as processed
		processed[pattern.ThenBlock] = true
		
		// Continue with merge block
		if pattern.EndLabel != "" && !processed[pattern.EndLabel] {
			e.generateBlockWithPatterns(pattern.EndLabel, blocks, patterns, sb, processed, indent)
		}
	}
}

// generateWhile generates a while loop
func (e *Emitter) generateWhile(
	pattern *llvm.ControlFlowPattern,
	blocks map[string]*llvm.BasicBlock,
	patterns []*llvm.ControlFlowPattern,
	sb *strings.Builder,
	processed map[string]bool,
	indent int,
) {
	condBlock := blocks[pattern.CondBlock]
	bodyBlock := blocks[pattern.BodyBlock]
	
	if condBlock == nil || bodyBlock == nil {
		return
	}
	
	indentStr := strings.Repeat("    ", indent)
	
	// Generate instructions in cond block before the branch (to compute condition)
	for i, inst := range condBlock.Instructions {
		// Skip the conditional branch at the end
		if i == len(condBlock.Instructions)-1 && strings.HasPrefix(inst, "br i1") {
			break
		}
		cLine := e.convertInstructionToC(inst)
		if cLine != "" {
			sb.WriteString(indentStr + cLine + "\n")
		}
	}
	
	// Generate while loop
	if condBlock.Terminator != nil && condBlock.Terminator.Condition != "" {
		condition := e.typeMapper.SanitizeName(condBlock.Terminator.Condition)
		sb.WriteString(fmt.Sprintf("%swhile (%s) {\n", indentStr, condition))
		
		// Generate loop body (excluding the back-edge branch)
		for i, inst := range bodyBlock.Instructions {
			// Skip unconditional branch back to condition
			if i == len(bodyBlock.Instructions)-1 && strings.HasPrefix(inst, "br label") {
				break
			}
			cLine := e.convertInstructionToC(inst)
			if cLine != "" {
				sb.WriteString(strings.Repeat("    ", indent+1) + cLine + "\n")
			}
		}
		
		// Re-evaluate condition at end of loop (for variables modified in body)
		for i, inst := range condBlock.Instructions {
			// Skip the conditional branch at the end
			if i == len(condBlock.Instructions)-1 && strings.HasPrefix(inst, "br i1") {
				break
			}
			cLine := e.convertInstructionToC(inst)
			if cLine != "" {
				sb.WriteString(strings.Repeat("    ", indent+1) + cLine + "\n")
			}
		}
		
		sb.WriteString(fmt.Sprintf("%s}\n", indentStr))
		
		// Mark blocks as processed
		processed[pattern.CondBlock] = true
		processed[pattern.BodyBlock] = true
		
		// Continue with code after loop
		if pattern.EndLabel != "" && !processed[pattern.EndLabel] {
			e.generateBlockWithPatterns(pattern.EndLabel, blocks, patterns, sb, processed, indent)
		}
	}
}

// generateFor generates a for loop
func (e *Emitter) generateFor(
	pattern *llvm.ControlFlowPattern,
	blocks map[string]*llvm.BasicBlock,
	patterns []*llvm.ControlFlowPattern,
	sb *strings.Builder,
	processed map[string]bool,
	indent int,
) {
	initBlock := blocks[pattern.InitBlock]
	condBlock := blocks[pattern.CondBlock]
	bodyBlock := blocks[pattern.BodyBlock]
	incrBlock := blocks[pattern.IncrBlock]
	
	if initBlock == nil || condBlock == nil || bodyBlock == nil || incrBlock == nil {
		return
	}
	
	indentStr := strings.Repeat("    ", indent)
	
	// Generate initialization code (before for statement)
	var initStatements []string
	for i, inst := range initBlock.Instructions {
		// Skip the unconditional branch at the end
		if i == len(initBlock.Instructions)-1 && strings.HasPrefix(inst, "br label") {
			break
		}
		cLine := e.convertInstructionToC(inst)
		if cLine != "" {
			initStatements = append(initStatements, cLine)
		}
	}
	
	// Generate condition evaluation code (to get the condition variable)
	var condStatements []string
	var conditionVar string
	for i, inst := range condBlock.Instructions {
		// Skip the conditional branch at the end
		if i == len(condBlock.Instructions)-1 && strings.HasPrefix(inst, "br i1") {
			break
		}
		cLine := e.convertInstructionToC(inst)
		if cLine != "" {
			condStatements = append(condStatements, cLine)
			// Extract the variable name from assignment (last statement before condition)
			if strings.Contains(cLine, "bool") && strings.Contains(cLine, "=") {
				parts := strings.SplitN(cLine, "=", 2)
				if len(parts) == 2 {
					varPart := strings.TrimSpace(strings.TrimPrefix(parts[0], "bool"))
					conditionVar = strings.TrimSpace(varPart)
				}
			}
		}
	}
	
	// If we have a condition variable from the terminator
	if conditionVar == "" && condBlock.Terminator != nil && condBlock.Terminator.Condition != "" {
		conditionVar = e.typeMapper.SanitizeName(condBlock.Terminator.Condition)
	}
	
	// Generate increment code
	var incrStatements []string
	for i, inst := range incrBlock.Instructions {
		// Skip the unconditional branch back to condition
		if i == len(incrBlock.Instructions)-1 && strings.HasPrefix(inst, "br label") {
			break
		}
		cLine := e.convertInstructionToC(inst)
		if cLine != "" {
			incrStatements = append(incrStatements, cLine)
		}
	}
	
	// Output initialization statements before the for loop
	for _, stmt := range initStatements {
		sb.WriteString(indentStr + stmt + "\n")
	}
	
	// Output condition evaluation before the for loop (for initial condition)
	for _, stmt := range condStatements {
		sb.WriteString(indentStr + stmt + "\n")
	}
	
	// Generate for loop with simplified structure
	// for (; condition; increment)
	sb.WriteString(fmt.Sprintf("%sfor (; %s; ", indentStr, conditionVar))
	
	// Write increment as inline expression (simplified)
	if len(incrStatements) > 0 {
		// Try to extract simple increment expression
		lastIncr := incrStatements[len(incrStatements)-1]
		// Remove semicolon and extract expression
		lastIncr = strings.TrimSuffix(lastIncr, ";")
		// Check if it's a simple assignment we can use
		if strings.Contains(lastIncr, "=") {
			parts := strings.SplitN(lastIncr, "=", 2)
			if len(parts) == 2 {
				sb.WriteString(strings.TrimSpace(parts[0]) + " = " + strings.TrimSpace(parts[1]))
			}
		}
	}
	sb.WriteString(") {\n")
	
	// Generate loop body (excluding the branch to increment)
	for i, inst := range bodyBlock.Instructions {
		// Skip unconditional branch to increment block
		if i == len(bodyBlock.Instructions)-1 && strings.HasPrefix(inst, "br label") {
			break
		}
		cLine := e.convertInstructionToC(inst)
		if cLine != "" {
			sb.WriteString(strings.Repeat("    ", indent+1) + cLine + "\n")
		}
	}
	
	// Re-evaluate condition at end of loop body (for variables modified in body)
	for _, stmt := range condStatements {
		sb.WriteString(strings.Repeat("    ", indent+1) + stmt + "\n")
	}
	
	sb.WriteString(fmt.Sprintf("%s}\n", indentStr))
	
	// Mark blocks as processed
	processed[pattern.InitBlock] = true
	processed[pattern.CondBlock] = true
	processed[pattern.BodyBlock] = true
	processed[pattern.IncrBlock] = true
	
	// Continue with code after loop
	if pattern.EndLabel != "" && !processed[pattern.EndLabel] {
		e.generateBlockWithPatterns(pattern.EndLabel, blocks, patterns, sb, processed, indent)
	}
}

// generateBasicBlock generates a basic block as-is (fallback)
func (e *Emitter) generateBasicBlock(
	label string,
	block *llvm.BasicBlock,
	sb *strings.Builder,
	indent int,
) {
	indentStr := strings.Repeat("    ", indent)
	
	// Generate label
	if label != "entry" {
		sb.WriteString(fmt.Sprintf("%s%s:\n", indentStr, label))
	}
	
	// Generate instructions
	for _, inst := range block.Instructions {
		cLine := e.convertInstructionToC(inst)
		if cLine != "" {
			sb.WriteString(indentStr + cLine + "\n")
		}
	}
	
	// Generate terminator
	if block.Terminator != nil {
		var termInst string
		switch block.Terminator.Type {
		case "ret":
			termInst = "ret"
		case "br_uncon":
			termInst = fmt.Sprintf("br label %%%s", block.Terminator.UnconLabel)
		case "br_cond":
			termInst = fmt.Sprintf("br i1 %s, label %%%s, label %%%s",
				block.Terminator.Condition,
				block.Terminator.TrueLabel,
				block.Terminator.FalseLabel)
		}
		
		if termInst != "" {
			cLine := e.convertInstructionToC(termInst)
			if cLine != "" {
				sb.WriteString(indentStr + cLine + "\n")
			}
		}
	}
}

// generateSwitch generates a C switch statement
func (e *Emitter) generateSwitch(
	pattern *llvm.ControlFlowPattern,
	blocks map[string]*llvm.BasicBlock,
	patterns []*llvm.ControlFlowPattern,
	sb *strings.Builder,
	processed map[string]bool,
	indent int,
) {
	indentStr := strings.Repeat("    ", indent)
	
	// Mark the switch block itself as processed
	processed[pattern.StartLabel] = true
	
	// Get the switch value and sanitize it
	switchValue := e.typeMapper.SanitizeName(pattern.SwitchValue)
	
	// Generate switch statement
	sb.WriteString(fmt.Sprintf("%sswitch (%s) {\n", indentStr, switchValue))
	
	// Generate case statements
	for _, switchCase := range pattern.SwitchCases {
		caseBlock := blocks[switchCase.Label]
		if caseBlock == nil {
			continue
		}
		
		// Generate case label
		sb.WriteString(fmt.Sprintf("%scase %s:\n", indentStr, switchCase.Value))
		
		// Mark as processed
		processed[switchCase.Label] = true
		
		// Generate case body
		for _, inst := range caseBlock.Instructions {
			// Check if this is a return statement - if so, don't add break
			if strings.HasPrefix(inst, "ret") {
				cLine := e.convertInstructionToC(inst)
				if cLine != "" {
					sb.WriteString(strings.Repeat("    ", indent+1) + cLine + "\n")
				}
				// No break needed after return
				continue
			}
			
			cLine := e.convertInstructionToC(inst)
			if cLine != "" {
				sb.WriteString(strings.Repeat("    ", indent+1) + cLine + "\n")
			}
		}
		
		// Check if we need a break statement
		// Only add break if the case doesn't end with return or goto
		if caseBlock.Terminator != nil {
			if caseBlock.Terminator.Type == "br_uncon" {
				// Unconditional branch - could be fallthrough or break
				// For now, treat as explicit break unless it's to the next case
				// This is a simplified implementation
				sb.WriteString(strings.Repeat("    ", indent+1) + "break;\n")
			}
			// If terminator is "ret", no break needed (already handled above)
		} else {
			// No terminator, add break to be safe
			sb.WriteString(strings.Repeat("    ", indent+1) + "break;\n")
		}
	}
	
	// Generate default case
	if pattern.DefaultLabel != "" {
		defaultBlock := blocks[pattern.DefaultLabel]
		if defaultBlock != nil {
			sb.WriteString(fmt.Sprintf("%sdefault:\n", indentStr))
			
			// Mark as processed
			processed[pattern.DefaultLabel] = true
			
			// Generate default body
			for _, inst := range defaultBlock.Instructions {
				if strings.HasPrefix(inst, "ret") {
					cLine := e.convertInstructionToC(inst)
					if cLine != "" {
						sb.WriteString(strings.Repeat("    ", indent+1) + cLine + "\n")
					}
					continue
				}
				
				cLine := e.convertInstructionToC(inst)
				if cLine != "" {
					sb.WriteString(strings.Repeat("    ", indent+1) + cLine + "\n")
				}
			}
			
			// Add break for default if needed
			if defaultBlock.Terminator != nil {
				if defaultBlock.Terminator.Type == "br_uncon" {
					sb.WriteString(strings.Repeat("    ", indent+1) + "break;\n")
				}
			} else {
				sb.WriteString(strings.Repeat("    ", indent+1) + "break;\n")
			}
		}
	}
	
	// Close switch statement
	sb.WriteString(fmt.Sprintf("%s}\n", indentStr))
}

// generateAggregateTypeDefinition generates a C struct definition for an aggregate type
func (e *Emitter) generateAggregateTypeDefinition(aggType *AggregateType) string {
	var sb strings.Builder
	
	sb.WriteString(fmt.Sprintf("typedef struct {\n"))
	
	// Generate fields
	for i, fieldType := range aggType.FieldTypes {
		cType := e.typeMapper.LLVMTypeToC(fieldType)
		sb.WriteString(fmt.Sprintf("    %s field%d;\n", cType, i))
	}
	
	sb.WriteString(fmt.Sprintf("} %s;", aggType.Name))
	
	return sb.String()
}

// convertInsertValueInstruction converts an insertvalue instruction to C
// Example: %result = insertvalue {i32, i32} undef, i32 %x, 0
// Becomes: result.field0 = x;
func (e *Emitter) convertInsertValueInstruction(instruction string) string {
	// Parse the instruction
	parts := strings.SplitN(instruction, "=", 2)
	if len(parts) != 2 {
		return fmt.Sprintf("/* %s */", instruction)
	}

	lhs := strings.TrimSpace(parts[0])
	rhs := strings.TrimSpace(parts[1])
	lhs = e.typeMapper.SanitizeName(lhs)

	// Parse: insertvalue {type} aggregate, type value, index
	// Example: insertvalue {i32, i32} undef, i32 %x, 0
	re := regexp.MustCompile(`insertvalue\s+(\{[^}]+\})\s+(\S+),\s+(\S+)\s+(\S+),\s+(\d+)`)
	matches := re.FindStringSubmatch(rhs)

	if len(matches) < 6 {
		return fmt.Sprintf("/* %s */", instruction)
	}

	aggregateType := matches[1]
	aggregateValue := matches[2]
	valueToInsert := matches[4]
	index := matches[5]

	// Get C type for aggregate
	cType := e.typeMapper.LLVMTypeToC(aggregateType)

	// Sanitize the value to insert (unless it's a literal)
	sanitizedValue := valueToInsert
	if _, err := strconv.Atoi(valueToInsert); err != nil {
		// It's a variable, sanitize it
		sanitizedValue = e.typeMapper.SanitizeName(valueToInsert)
	}

	// Handle "undef" - this means we're creating a new struct
	if aggregateValue == "undef" {
		// Declare the struct variable if it's the first insertvalue
		return fmt.Sprintf("%s %s; %s.field%s = %s;", cType, lhs, lhs, index, sanitizedValue)
	}

	// Otherwise, we're modifying an existing struct
	sanitizedAggregate := e.typeMapper.SanitizeName(aggregateValue)
	return fmt.Sprintf("%s %s = %s; %s.field%s = %s;", cType, lhs, sanitizedAggregate, lhs, index, sanitizedValue)
}

// convertExtractValueInstruction converts an extractvalue instruction to C
// Example: %val1 = extractvalue {i32, i32} %0, 0
// Becomes: int val1 = var_0.field0;
func (e *Emitter) convertExtractValueInstruction(instruction string) string {
	// Parse the instruction
	parts := strings.SplitN(instruction, "=", 2)
	if len(parts) != 2 {
		return fmt.Sprintf("/* %s */", instruction)
	}

	lhs := strings.TrimSpace(parts[0])
	rhs := strings.TrimSpace(parts[1])
	lhs = e.typeMapper.SanitizeName(lhs)

	// Parse: extractvalue {type} aggregate, index
	// Example: extractvalue {i32, i32} %0, 0
	re := regexp.MustCompile(`extractvalue\s+(\{[^}]+\})\s+(\S+),\s+(\d+)`)
	matches := re.FindStringSubmatch(rhs)

	if len(matches) < 4 {
		return fmt.Sprintf("/* %s */", instruction)
	}

	aggregateType := matches[1]
	aggregateValue := matches[2]
	index := matches[3]

	// Parse aggregate type to get field type
	fieldTypes := e.typeMapper.parseAggregateFields(aggregateType)
	indexInt, err := strconv.Atoi(index)
	if err != nil || indexInt >= len(fieldTypes) {
		return fmt.Sprintf("/* %s */", instruction)
	}

	fieldType := e.typeMapper.LLVMTypeToC(fieldTypes[indexInt])
	sanitizedAggregate := e.typeMapper.SanitizeName(aggregateValue)

	return fmt.Sprintf("%s %s = %s.field%s;", fieldType, lhs, sanitizedAggregate, index)
}
