package codegen

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/opd-ai/go2c/internal/llvm"
)

// Emitter generates C code from LLVM IR
type Emitter struct {
	typeMapper *TypeMapper
	includes   []string
	defines    []string
}

// NewEmitter creates a new C code emitter
func NewEmitter() *Emitter {
	return &Emitter{
		typeMapper: NewTypeMapper(),
		includes: []string{
			"stdio.h",
			"stdlib.h",
			"string.h",
			"stdint.h",
			"stdbool.h",
		},
		defines: []string{},
	}
}

// Emit generates C code from an LLVM module
func (e *Emitter) Emit(module *llvm.Module) (string, error) {
	var sb strings.Builder

	// Write file header comment
	sb.WriteString("// Generated by go2c - Go to C transpiler\n")
	sb.WriteString("// DO NOT EDIT - Generated code\n\n")

	// Write includes
	for _, include := range e.includes {
		sb.WriteString(fmt.Sprintf("#include <%s>\n", include))
	}
	sb.WriteString("\n")

	// Write defines
	for _, define := range e.defines {
		sb.WriteString(fmt.Sprintf("#define %s\n", define))
	}
	if len(e.defines) > 0 {
		sb.WriteString("\n")
	}

	// Write forward declarations for user functions
	analyzer := llvm.NewAnalyzer(module)
	userFunctions := analyzer.GetUserFunctions()
	
	if len(userFunctions) > 0 {
		sb.WriteString("// Forward declarations\n")
		for _, fn := range userFunctions {
			decl := e.generateFunctionDeclaration(fn)
			sb.WriteString(decl + ";\n")
		}
		sb.WriteString("\n")
	}

	// Write global variables
	if len(module.Globals) > 0 {
		sb.WriteString("// Global variables\n")
		for _, global := range module.Globals {
			globalDecl := e.generateGlobalVariable(global)
			if globalDecl != "" {
				sb.WriteString(globalDecl + "\n")
			}
		}
		sb.WriteString("\n")
	}

	// Write function definitions
	sb.WriteString("// Function implementations\n")
	for _, fn := range userFunctions {
		fnCode := e.generateFunction(fn)
		sb.WriteString(fnCode)
		sb.WriteString("\n")
	}

	return sb.String(), nil
}

// generateFunctionDeclaration generates a C function declaration
func (e *Emitter) generateFunctionDeclaration(fn *llvm.Function) string {
	returnType := e.typeMapper.LLVMTypeToC(fn.ReturnType)
	funcName := e.typeMapper.SanitizeName(fn.Name)

	// Build parameter list
	params := []string{}
	if len(fn.Parameters) == 0 {
		params = append(params, "void")
	} else {
		for i, param := range fn.Parameters {
			paramType := e.typeMapper.LLVMTypeToC(param.Type)
			paramName := e.typeMapper.SanitizeName(param.Name)
			if paramName == "" {
				paramName = fmt.Sprintf("param%d", i)
			}
			params = append(params, fmt.Sprintf("%s %s", paramType, paramName))
		}
	}

	return fmt.Sprintf("%s %s(%s)", returnType, funcName, strings.Join(params, ", "))
}

// generateFunction generates a complete C function
func (e *Emitter) generateFunction(fn *llvm.Function) string {
	var sb strings.Builder

	// Function declaration
	sb.WriteString(e.generateFunctionDeclaration(fn))
	sb.WriteString(" {\n")

	// Function body
	if len(fn.Body) == 0 {
		sb.WriteString("    // Empty function body\n")
	} else {
		// Basic instruction conversion
		for _, line := range fn.Body {
			cLine := e.convertInstructionToC(line)
			if cLine != "" {
				sb.WriteString("    " + cLine + "\n")
			}
		}
	}

	sb.WriteString("}\n")
	return sb.String()
}

// convertInstructionToC converts an LLVM instruction to C code
func (e *Emitter) convertInstructionToC(instruction string) string {
	instruction = strings.TrimSpace(instruction)

	// Skip empty lines
	if instruction == "" {
		return ""
	}

	// Handle return instructions
	if strings.HasPrefix(instruction, "ret") {
		parts := strings.Fields(instruction)
		if len(parts) == 1 || parts[1] == "void" {
			return "return;"
		}
		// ret i32 0 or ret i32 %result
		if len(parts) >= 3 {
			value := parts[2]
			// Check if value is a literal number
			if _, err := strconv.Atoi(value); err != nil {
				// It's a variable, sanitize it
				value = e.typeMapper.SanitizeName(value)
			}
			return fmt.Sprintf("return %s;", value)
		}
		return "return;"
	}

	// Handle assignment with arithmetic operations
	// Example: %result = add i32 %a, %b
	if strings.Contains(instruction, "=") && !strings.Contains(instruction, "call") {
		return e.convertAssignmentInstruction(instruction)
	}

	// Handle call instructions
	if strings.Contains(instruction, "call") {
		return e.convertCallInstruction(instruction)
	}

	// Handle alloca (stack allocation)
	if strings.Contains(instruction, "alloca") {
		return e.convertAllocaInstruction(instruction)
	}

	// Handle store instructions
	if strings.HasPrefix(instruction, "store") {
		return e.convertStoreInstruction(instruction)
	}

	// Handle load instructions
	if strings.Contains(instruction, "load") {
		return e.convertLoadInstruction(instruction)
	}

	// Handle branch instructions
	if strings.HasPrefix(instruction, "br") {
		return e.convertBranchInstruction(instruction)
	}

	// Handle label declarations
	if strings.HasSuffix(instruction, ":") {
		labelName := strings.TrimSuffix(instruction, ":")
		labelName = e.typeMapper.SanitizeName(labelName)
		return fmt.Sprintf("%s:", labelName)
	}

	// Default: comment out unknown instructions
	return fmt.Sprintf("/* %s */", instruction)
}

// convertAssignmentInstruction converts an assignment instruction to C
func (e *Emitter) convertAssignmentInstruction(instruction string) string {
	// Example: %result = add i32 %a, %b
	parts := strings.SplitN(instruction, "=", 2)
	if len(parts) != 2 {
		return fmt.Sprintf("/* %s */", instruction)
	}

	lhs := strings.TrimSpace(parts[0])
	rhs := strings.TrimSpace(parts[1])
	lhs = e.typeMapper.SanitizeName(lhs)

	// Parse the operation
	rhsParts := strings.Fields(rhs)
	if len(rhsParts) == 0 {
		return fmt.Sprintf("/* %s */", instruction)
	}

	op := rhsParts[0]

	switch op {
	case "add", "sub", "mul", "sdiv", "udiv", "srem", "urem":
		if len(rhsParts) >= 4 {
			// add i32 %a, %b
			cType := e.typeMapper.LLVMTypeToC(rhsParts[1])
			operand1 := strings.TrimSuffix(e.typeMapper.SanitizeName(rhsParts[2]), ",")
			operand2 := e.typeMapper.SanitizeName(rhsParts[3])
			
			var operator string
			switch op {
			case "add":
				operator = "+"
			case "sub":
				operator = "-"
			case "mul":
				operator = "*"
			case "sdiv", "udiv":
				operator = "/"
			case "srem", "urem":
				operator = "%"
			}
			
			return fmt.Sprintf("%s %s = %s %s %s;", cType, lhs, operand1, operator, operand2)
		}
	}

	return fmt.Sprintf("/* %s */", instruction)
}

// convertAllocaInstruction converts an alloca instruction to C
func (e *Emitter) convertAllocaInstruction(instruction string) string {
	// Example: %ptr = alloca i32
	parts := strings.SplitN(instruction, "=", 2)
	if len(parts) != 2 {
		return fmt.Sprintf("/* %s */", instruction)
	}

	lhs := strings.TrimSpace(parts[0])
	rhs := strings.TrimSpace(parts[1])
	lhs = e.typeMapper.SanitizeName(lhs)

	rhsParts := strings.Fields(rhs)
	if len(rhsParts) >= 2 && rhsParts[0] == "alloca" {
		allocType := e.typeMapper.LLVMTypeToC(rhsParts[1])
		return fmt.Sprintf("%s %s;", allocType, lhs)
	}

	return fmt.Sprintf("/* %s */", instruction)
}

// convertStoreInstruction converts a store instruction to C
func (e *Emitter) convertStoreInstruction(instruction string) string {
	// Example: store i32 %value, i32* %ptr
	parts := strings.Fields(instruction)
	if len(parts) >= 5 {
		value := e.typeMapper.SanitizeName(parts[2])
		value = strings.TrimSuffix(value, ",")
		dest := e.typeMapper.SanitizeName(parts[4])
		return fmt.Sprintf("*%s = %s;", dest, value)
	}
	return fmt.Sprintf("/* %s */", instruction)
}

// convertLoadInstruction converts a load instruction to C
func (e *Emitter) convertLoadInstruction(instruction string) string {
	// Example: %value = load i32, i32* %ptr
	parts := strings.SplitN(instruction, "=", 2)
	if len(parts) != 2 {
		return fmt.Sprintf("/* %s */", instruction)
	}

	lhs := strings.TrimSpace(parts[0])
	rhs := strings.TrimSpace(parts[1])
	lhs = e.typeMapper.SanitizeName(lhs)

	rhsParts := strings.Fields(rhs)
	if len(rhsParts) >= 3 && rhsParts[0] == "load" {
		loadType := e.typeMapper.LLVMTypeToC(rhsParts[1])
		loadType = strings.TrimSuffix(loadType, ",")
		src := e.typeMapper.SanitizeName(rhsParts[len(rhsParts)-1])
		return fmt.Sprintf("%s %s = *%s;", loadType, lhs, src)
	}

	return fmt.Sprintf("/* %s */", instruction)
}

// convertCallInstruction converts a call instruction to C
func (e *Emitter) convertCallInstruction(instruction string) string {
	// Parse call instruction
	// Example: call void @puts(i8* %1)
	// Example: %0 = call i32 @add(i32 5, i32 3)
	
	hasAssignment := strings.Contains(instruction, "=")
	var lhs string
	var callPart string
	
	if hasAssignment {
		parts := strings.SplitN(instruction, "=", 2)
		lhs = e.typeMapper.SanitizeName(strings.TrimSpace(parts[0]))
		callPart = strings.TrimSpace(parts[1])
	} else {
		callPart = instruction
	}
	
	// Extract function name
	if !strings.Contains(callPart, "@") {
		return fmt.Sprintf("/* %s */", instruction)
	}
	
	atIndex := strings.Index(callPart, "@")
	afterAt := callPart[atIndex+1:]
	parenIndex := strings.Index(afterAt, "(")
	
	if parenIndex == -1 {
		return fmt.Sprintf("/* %s */", instruction)
	}
	
	funcName := e.typeMapper.SanitizeName(afterAt[:parenIndex])
	
	// Extract arguments
	argsStart := atIndex + 1 + parenIndex + 1
	argsEnd := strings.LastIndex(callPart, ")")
	
	if argsEnd == -1 {
		argsEnd = len(callPart)
	}
	
	argsStr := ""
	if argsStart < argsEnd {
		argsPart := callPart[argsStart:argsEnd]
		args := e.parseCallArguments(argsPart)
		argsStr = strings.Join(args, ", ")
	}
	
	// Generate C code
	if hasAssignment {
		// Extract return type
		callFields := strings.Fields(callPart)
		var returnType string
		if len(callFields) >= 2 {
			returnType = e.typeMapper.LLVMTypeToC(callFields[1])
		} else {
			returnType = "int"
		}
		return fmt.Sprintf("%s %s = %s(%s);", returnType, lhs, funcName, argsStr)
	}
	
	return fmt.Sprintf("%s(%s);", funcName, argsStr)
}

// parseCallArguments parses function call arguments
func (e *Emitter) parseCallArguments(argsStr string) []string {
	if strings.TrimSpace(argsStr) == "" {
		return []string{}
	}
	
	args := []string{}
	parts := strings.Split(argsStr, ",")
	
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		
		// Parse "type value" format
		tokens := strings.Fields(part)
		if len(tokens) >= 2 {
			value := tokens[len(tokens)-1]
			// Check if value is a literal number
			if _, err := strconv.Atoi(value); err == nil {
				args = append(args, value)
			} else {
				value = e.typeMapper.SanitizeName(value)
				args = append(args, value)
			}
		} else if len(tokens) == 1 {
			value := tokens[0]
			if _, err := strconv.Atoi(value); err == nil {
				args = append(args, value)
			} else {
				value = e.typeMapper.SanitizeName(value)
				args = append(args, value)
			}
		}
	}
	
	return args
}

// convertBranchInstruction converts a branch instruction to C
func (e *Emitter) convertBranchInstruction(instruction string) string {
	// br label %label1 -> goto label1;
	if strings.Contains(instruction, "label") {
		parts := strings.Fields(instruction)
		for i, part := range parts {
			if part == "label" && i+1 < len(parts) {
				label := e.typeMapper.SanitizeName(parts[i+1])
				return fmt.Sprintf("goto %s;", label)
			}
		}
	}
	// Conditional branch: br i1 %cond, label %true, label %false
	if strings.Contains(instruction, ",") {
		return "/* conditional branch - if/goto */"
	}
	return "/* branch instruction */"
}

// generateGlobalVariable generates a C global variable declaration
func (e *Emitter) generateGlobalVariable(global *llvm.Global) string {
	name := e.typeMapper.SanitizeName(global.Name)
	
	// Handle string constants
	if strings.Contains(global.Value, "constant") && strings.Contains(global.Value, "c\"") {
		// Extract string value
		if idx := strings.Index(global.Value, "c\""); idx != -1 {
			strPart := global.Value[idx+2:]
			if endIdx := strings.Index(strPart, "\""); endIdx != -1 {
				strValue := strPart[:endIdx]
				// Unescape common escapes
				strValue = strings.ReplaceAll(strValue, "\\00", "\\0")
				strValue = strings.ReplaceAll(strValue, "\\0A", "\\n")
				return fmt.Sprintf("static const char %s[] = \"%s\";", name, strValue)
			}
		}
	}
	
	// Default handling for other globals
	return fmt.Sprintf("/* Global: %s */", name)
}

// AddInclude adds a custom include file
func (e *Emitter) AddInclude(include string) {
	e.includes = append(e.includes, include)
}

// AddDefine adds a preprocessor define
func (e *Emitter) AddDefine(define string) {
	e.defines = append(e.defines, define)
}
